### ISSUE TITLE
[FEATURE REQUEST] Add support for associating projects with multiple TAGs

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/landscape2#777]
Currently there is a one-to-one mapping of CNCF TAG to project, however many projects actually span more than one TAG and may have multiple TAGs involved in their review when moving levels. As far as  I can tell, the tag variable is only used for filters so hopefully a change like this would not be very disruptive.

Current:
```yaml
item:
   name: foo
   ...
    extra:
      tag: bar
```

Desired:
```yaml
item:
   name: foo
   ...
    extra:
      tag:
        - bar
        - baz
```
